# Apuntamos a una base de datos limpia de pruebas
spring.datasource.url=jdbc:postgresql://localhost:5432/autotrack_dev

# Aquí va el truco: limpia y recrea solo la base de datos de pruebas cada vez que corra el script
spring.jpa.hibernate.ddl-auto=create-drop

spring.security.user.name=user
spring.security.user.password=gayelquelolea