spring.application.name=autotrack_apicore
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/autotrack_db

# ponga sus respectivas credenciales
spring.datasource.username = postgres
spring.datasource.password = Carnedeldiablo17@

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibertnate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
