# Se activa con spring.profiles.active=staging
spring.datasource.url=jdbc:postgresql://localhost:5432/autotrack_staging

# Los datos se quedan guardados de forma permanente para las pruebas.
spring.jpa.hibernate.ddl-auto=update